#!/bin/bash
# install_typora
#   Draft: 2020-10-16 (Fri)
# Usage:
#   $ chmod +x install_typora
#   $ ./install_typora

wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -

# add Typora's repository
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt-get update

# install typora
sudo apt-get install -y typora
