#!/bin/bash
# fetch_batch_git
#   fetches batch_git_push and batch_git_pull to the current directory
#
# * Draft: 2020-03-01 (Sun)

CMD="./batch_git_pull"
echo $CMD
eval $CMD

CMD="cp computing_environments/git/batch_git_pu** ."
echo $CMD
eval $CMD
