#!/bin/bash

# install_opencv_in_linux
#### Install OpenCV dependencies

sudo apt update
sudo apt upgrade -y

#### C/C++ compiler, make, compile option, etc.
sudo apt install -y build-essential cmake unzip pkg-config 

#### Image I/O packages for the standard image file formats, e.g.  JPEG, PNG, TIFF, etc
sudo apt -y install libjpeg-dev libpng-dev libtiff-dev
sudo apt -y install libjasper-dev

#### Video I/O Packages I/O packages for camera stream & video files
sudo apt install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev v4l-utils libxvidcore-d$

####  GStreamer for video streaming
sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev 

#### OpenCV ^`^ys highgui module relies on the GTK library for GUI operations
sudo apt install -y libgtk-3-dev

#### sudo apt install -y libgtk-3-dev libqt4-dev libqt5-dev

#### OpenGL support
sudo apt install -y mesa-utils libgl1-mesa-dri libgtkgl2.0-dev libgtkglext1-dev

#### Optimization of OpenCV 
sudo apt install -y libatlas-base-dev gfortran libeigen3-dev

#### OpenCV-Python binding
sudo apt-get install -y python3-dev