#!/bin/bash
# install_opencv
###   * Draft: 2021-01-27 (Wed)

## Step 0. Install Anaconda

### Download

wget https://repo.anaconda.com/archive/Anaconda3-2020.07-Linux-x86_64.sh

### Install

bash Anaconda3-2020.07-Linux-x86_64.sh

### Create a virtual environment



## Step 1. Install dependencies
sudo apt update
sudo apt upgrade -y

### C/C++ compiler, make, compile option, etc.
sudo apt install -y build-essential cmake unzip pkg-config 

### Image I/O packages for the standard image file formats, e.g.  JPEG, PNG, TIFF, etc
sudo apt -y install libjpeg-dev libpng-dev libtiff-dev
sudo apt -y install libjasper-dev

### Video I/O Packages I/O packages for camera stream & video files
sudo apt install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev v4l-utils libxvidcore-dev libx264-dev

###  GStreamer for video streaming
sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev 

### OpenCV’s highgui module relies on the GTK library for GUI operations
sudo apt install -y libgtk-3-dev

### sudo apt install -y libgtk-3-dev libqt4-dev libqt5-dev
### OpenGL support
sudo apt install -y mesa-utils libgl1-mesa-dri libgtkgl2.0-dev libgtkglext1-dev

### Optimization of OpenCV 
sudo apt install -y libatlas-base-dev gfortran libeigen3-dev

### OpenCV-Python binding
### Python 3 headers & libraries

#### 아래 명령어를 추가했으나 이미 최신 버전이 설치되어 있었음.
sudo apt install -y python2.7-dev python3-dev python-numpy python3-numpy

## Step 2. Install OpenCV

### Download the installation file
wget https://github.com/opencv/opencv/archive/4.5.1.zip
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.5.1.zip
unzip opencv_contrib.zip 

### Compile it
cd opencv-4.5.1/
mkdir build
cd build/
cmake -D CMAKE_BUILD_TYPE=RELEASE \
> -D CMAKE_INSTALL_PREFIX=/usr/local \
> -D WITH_TBB=OFF \
> -D WITH_IPP=OFF \
> -D WITH_1394=OFF \
> -D BUILD_WITH_DEBUG_INFO=OFF \
> -D BUILD_DOCS=OFF \
> -D INSTALL_C_EXAMPLES=ON \
> -D INSTALL_PYTHON_EXAMPLES=ON \
> -D BUILD_EXAMPLES=OFF \
> -D BUILD_TESTS=OFF \
> -D BUILD_PERF_TESTS=OFF \
> -D WITH_QT=OFF \
> -D WITH_GTK=ON \
> -D WITH_OPENGL=ON \
> -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.5.1/modules \
> -D WITH_V4L=ON  \
> -D WITH_FFMPEG=ON \
> -D WITH_XINE=ON \
> -D BUILD_NEW_PYTHON_SUPPORT=ON \
> -D OPENCV_GENERATE_PKGCONFIG=ON ../