#!/bin/bash
# install_opencv_in_linux
####   Installation in Linux
#####     https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html

#### Build core modules
##### is not adapted.

#### Build with opencv_contrib
##### Install minimal prerequisites (Ubuntu 18.04 as reference)
sudo apt update && sudo apt install -y cmake g++ wget unzip

##### Download and unpack sources
wget -O opencv.zip https://github.com/opencv/opencv/archive/master.zip
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/master.zip
unzip opencv.zip
unzip opencv_contrib.zip

##### Create build directory
mkdir -p build && cd build

##### Configure
cmake -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-master/modules ../opencv-master

##### Build
cmake --build .


