#!/bin/bash
# run_docker_build

export IMAGE_NAME='nvidia/cuda'
docker build -t baseimage-darknet:cudnn8-devel-ubuntu20.04 --build-arg IMAGE_NAME=$IMAGE_NAME .
docker run -it baseimage-darknet:cudnn8-devel-ubuntu20.04 bash

# To check NVCC, CUDA, & CUDNN, run:
#   # nvcc --version
#   # cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#   # nvidia-smi
