#!/bin/bash

# install_opencv_in_linux
#### Install OpenCV dependencies

apt update
apt upgrade -y

#### C/C++ compiler, make, compile option, etc.

apt install -y build-essential cmake unzip pkg-config 

#### Image I/O packages for the standard image file formats, e.g.  JPEG, PNG, TIFF, etc

apt -y install libjpeg-dev libpng-dev libtiff-dev
apt -y install libjasper-dev

#### Video I/O Packages I/O packages for camera stream & video files

apt install -y libavcodec-dev libavformat-dev libswscale-dev libv4l-dev v4l-utils libxvidcore-dev libx264-dev

####  GStreamer for video streaming

apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev 

#### OpenCV’s highgui module relies on the GTK library for GUI operations

apt install -y libgtk-3-dev

#### apt install -y libgtk-3-dev libqt4-dev libqt5-dev

#### OpenGL support

apt install -y mesa-utils libgl1-mesa-dri libgtkgl2.0-dev libgtkglext1-dev

#### Optimization of OpenCV 

apt install -y libatlas-base-dev gfortran libeigen3-dev

#### OpenCV-Python binding

apt-get install -y python3-dev

####   Installation in Linux

#####     https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html

#### Build core modules
##### is not adapted.

#### Build with opencv_contrib
##### Install minimal prerequisites (Ubuntu 18.04 as reference)
apt update && apt install -y cmake g++ wget unzip

##### Download and unpack sources
wget -O opencv.zip https://github.com/opencv/opencv/archive/master.zip
wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/master.zip
unzip opencv.zip
unzip opencv_contrib.zip

##### Create build directory
mkdir -p build && cd build

##### Configure
cmake -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-master/modules ../opencv-master

##### Build
cmake --build .

##### Install
make install
