#!/bin/bash
# cat_personal_access_token
#   This script run `cat personal_access_token` to print your personal access token
#   You can copy the printed personal access token and paste when you log into your Git account.
#
# * Draft: 2024-03-21 (Thu)
#
# Prerequisites
#   * Create a personal access token for your Git account.
#   * Save your personal access token in a more or like secure location.
#
# Usage
#   $ chmod +x cat_personal_access_token
#   $ ./cat_personal_access_token
#
# An example to save your personal access token
#   Assume the directory git is created and all files (batch*, *.cfg files) are copied. 
#   $ cd ~/git
#   $ nano personal_access_token-google_cloud-argolis-expires_on_2025-01-01
#   # copy & paste the personal access token to this file, save and exit.
#   $ mkdir .login
#   $ mv personal_access_token-google_cloud-argolis-expires_on_2025-01-01 .login
#   $ ln -s .login/personal_access_token-google_cloud-argolis-expires_on_2025-01-01 personal_access_token

# Don't change part this
cat personal_access_token
# Don't change this part
